# Generated by Django 4.0.4 on 2022-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ürün adını yazınız', max_length=200, unique=True, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='products/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
